### ISSUE TITLE
Configuration files

### ISSUE THREAD

**Issue by salahoued** [MagmaWM/MagmaWM#115]
Hello,
I have succeeded to compile Magma but I couldn't find any configuration file, and the documentation doesn't have any.

It would be good to have at least some config files ready for anyone interested in trying out Magma, while waiting for the documentation and the project to mature.

Thanks for all the work, and all the best.

**Comment by cinnamonpancake** [comment]
the stock config file should be automatically generated at ~/.config/magmawm/config.ron
that should probably be a bit clearer though

**Comment by salahoued** [comment]
@cinnamonpancake , thanks, that helpes, I managed to start it and trying it out.

**Comment by mfdorst** [comment]
I guess we should add that to the readme. I assume most people would look there first but I guess not everyone is used to editing configs.

**Comment by HackedOS** [comment]
Uhh probs should add a full example with all configurable options aswell

**Comment by salahoued** [comment]
@mfdorst , yes, I think The Readme files are the first landing of most new users, that will guide them to not only how to install or compile but also to how to use and configure, I didn't think it would regenerate a config file automatically, so I searched through the project folder for some config files and looking for documentation and wikis. mostly I am the who has to copy files to home config, 

@HackedOS , That would be much appreciated, and if the example has comments on the options would be even better.
I'd say that _labwc_ is my main compositor for the time, the config files (4) are contain all the configurable options at least commented
I have peeked at _niri_ today, and it automatically generate a config file with all its options some active and some not activated (commented) with explanations.

Lastly, I'd like to apologize for any inconveniences, but I appreciate your efforts and work,
Thanks

**Comment by HackedOS** [comment]
> @mfdorst , yes, I think The Readme files are the first landing of most new users, that will guide them to not only how to install or compile but also to how to use and configure, I didn't think it would regenerate a config file automatically, so I searched through the project folder for some config files and looking for documentation and wikis. mostly I am the who has to copy files to home config,
> 
> @HackedOS , That would be much appreciated, and if the example has comments on the options would be even better. I'd say that _labwc_ is my main compositor for the time, the config files (4) contain all the configurable options at least commented I have peeked at _niri_ today, and it automatically generate a config file with all its options some active and some not activated (commented) with explanations.
> 
> Lastly, I'd like to apologize for any inconveniences, but I appreciate your efforts and work, Thanks

Yes we will add a temporary config to the readme as we are switching to a different config format by the time we come around to a beta release
