### ISSUE TITLE
Tiling bugs on some programs

### ISSUE THREAD

**Issue by egreg10us** [MagmaWM/MagmaWM#6]
When some programs are launched(like mpv or Inkscape) they dont tile properly and i think when that program is launched it creates a private tiling area around itself

![IMG_20230513_222201](https://github.com/MagmaEWM/MagmaEWM/assets/119522164/8ea6cd62-c8bb-4bc2-8840-4cb9d47e2c0e)
![IMG_20230513_222156](https://github.com/MagmaEWM/MagmaEWM/assets/119522164/b6a51de4-73f4-41b0-b0f6-539ab651edcf)
![IMG_20230513_222137](https://github.com/MagmaEWM/MagmaEWM/assets/119522164/ce96a883-d1c7-4f39-ac5e-40b7e2ab74ea)
![IMG_20230513_222035](https://github.com/MagmaEWM/MagmaEWM/assets/119522164/063e2fbf-90cb-4b4e-99c0-577884ce92a9)

**Comment by egreg10us** [comment]
solved

**Comment by electron271** [comment]
if this is solved should i close the issue

**Comment by egreg10us** [comment]
> if this is solved should i close the issue

yes

**Comment by electron271** [comment]
i should note that this is likely a mpv issue, mpv refuses to resize as well on awesomewm
