### ISSUE TITLE
new config format

### ISSUE THREAD

**Issue by HackedOS** [MagmaWM/MagmaWM#63]
This issue exists to track the progress and implementation of a new custom config format for MagmaWM

**Comment by Aleksanaa** [comment]
We NixOS users no longer want yet another config format😭

**Comment by anantnrg** [comment]
A static config or a scriptable config?

**Comment by HackedOS** [comment]
> A static config or a scriptable config?
static config, but some basic variable parsing is possible

**Comment by anantnrg** [comment]
hmm... is this like completely from scratch (parsing the config with something like nom) or based on an existing format?

**Comment by HackedOS** [comment]
this is completely from scratch unless a good  proposal using an existing format comes into sight

**Comment by anantnrg** [comment]
KDL maybe? Looks pretty solid.

**Comment by nixos-goddess** [comment]
Toml

**Comment by anantnrg** [comment]
> Toml

Nah, dont make the same mistake that i did.

**Comment by nixos-goddess** [comment]
Ooooooorrr, hear me out

What if we

Just stayed on ron

**Comment by anantnrg** [comment]
> Ooooooorrr, hear me out

> What if we

> Just stayed on ron



Exactly my thought. Ron's fine. Maybe we should look into implementing more important things.

**Comment by HackedOS** [comment]
> > Ooooooorrr, hear me out
> 
> > What if we
> 
> > Just stayed on ron
> 
> Exactly my thought. Ron's fine. Maybe we should look into implementing more important things.

RON syntax is not intuitive for the target audience of MagmaWM

**Comment by nixos-goddess** [comment]
> RON syntax is not intuitive for the target audience of MagmaWM

They're linux users, they know that they gotta configure stuff, and the syntax isn't *that* bad

**Comment by HackedOS** [comment]
if we change the config and i think we will it should be before the first release

**Comment by electron271** [comment]
> > > Ooooooorrr, hear me out
> > 
> > 
> > > What if we
> > 
> > 
> > > Just stayed on ron
> > 
> > 
> > Exactly my thought. Ron's fine. Maybe we should look into implementing more important things.
> 
> RON syntax is not intuitive for the target audience of MagmaWM

If you know how to use a window manager, you know how to configure with RON. Also good documentation will help a lot.

If you really need a new syntax, consider toml or similar.

**Comment by anantnrg** [comment]
@HackedOS Do you have like a syntax you like, C-style, S-style?

**Comment by HackedOS** [comment]
> @HackedOS Do you have like a syntax you like, C-style, S-style?

not really im fine with whatever is preferred by most people. accessibility is most important

**Comment by anantnrg** [comment]
So are you looking to implement Lua now?

**Comment by HackedOS** [comment]
> So are you looking to implement Lua now?

it was just an option. still thinking

**Comment by anantnrg** [comment]
Nickel could do.

**Comment by TornaxO7** [comment]
I don't see an issue with ron. You are basically using strings, array like syntax and dictionary stuff if I remember correctly.

**Comment by nixos-goddess** [comment]
I don't think we should move from ron either. We also have priorities rn that are higher than changing config langs

**Comment by electron271** [comment]
Contributors agree this is not a good path, I will be closing this issue, We have much bigger priorities then fixing whats not broken.

Feel free to re-open this issue in the future when we have bigger issues sorted out and if this becomes more needed and less controversial.
