### ISSUE TITLE
wofi and bemenu don't display correctly

### ISSUE THREAD

**Issue by alonzo-bazaar** [MagmaWM/MagmaWM#81]
while using magmawm, if I spawn a `wofi` or `bemenu_run` process, it handles input and spawns programs as it should, but the `wofi`/`bemenu` window never updates

the issue was found on fedora 39 with magmawm installed from git main following the instructions in the readme

below is a recording of this behavior (with magmawm running on an x11 window, sorry for the quality and aspect ratio)

https://github.com/MagmaWM/MagmaWM/assets/132933465/ac2c4c7b-b09f-4ca8-b30f-1e31ae5e705d

log files obtained by running
```sh
export WAYLAND_DEBUG=1
sway &> sway_bemenu # use bemenu_run in sway
sway &> sway_wofi # use bemenu_run in sway
<magma run script> &> magma_bemenu # use bemenu_run in magma
<magma run script> &> magma_wofi # use wofi in magma
```
in a tty
[magma_bemenu.log](https://github.com/MagmaWM/MagmaWM/files/14850979/magma_bemenu.log)
[magma_wofi.log](https://github.com/MagmaWM/MagmaWM/files/14850980/magma_wofi.log)
[sway_bemenu.log](https://github.com/MagmaWM/MagmaWM/files/14850982/sway_bemenu.log)
[sway_wofi.log](https://github.com/MagmaWM/MagmaWM/files/14850984/sway_wofi.log)

the magma config
[config.ron.txt](https://github.com/MagmaWM/MagmaWM/files/14850994/config.ron.txt)

and the wofi config, if it's needed
[config.txt](https://github.com/MagmaWM/MagmaWM/files/14851038/config.txt)
[style.css.txt](https://github.com/MagmaWM/MagmaWM/files/14851047/style.css.txt)

(edit)
I provided the wrong logs, these logs were obtained by running
```sh
# in magmawm
wofi &> magma_wofi
bemenu-run &> magma_bemenu
# on sway
wofi &> sway_wofi
bemenu-run &> sway_bemenu
```

[magma_bemenu.log](https://github.com/MagmaWM/MagmaWM/files/14851477/magma_bemenu.log)
[magma_wofi.log](https://github.com/MagmaWM/MagmaWM/files/14851479/magma_wofi.log)
[sway_bemenu.log](https://github.com/MagmaWM/MagmaWM/files/14851480/sway_bemenu.log)
[sway_wofi.log](https://github.com/MagmaWM/MagmaWM/files/14851481/sway_wofi.log)

(the `.log` extension was added to let github upload the files to the issue)

**Comment by electron271** [comment]
able to reproduce using `wofi -d` via magmawm inside awesomewm, i cant type into it myself

will be testing further to see if i can reproduce, also reproduced with `fuzzel` (wofi is unmaintained, fuzzel recommended)

**Comment by Ottatop** [comment]
It's because no frames are getting sent to any layer surfaces.

Tacking on
```diff
diff --git a/src/backends/winit.rs b/src/backends/winit.rs
index a11f44e..4d5174f 100644
--- a/src/backends/winit.rs
+++ b/src/backends/winit.rs
@@ -343,6 +343,16 @@ pub fn winit_dispatch(
         )
     });
 
+    drop(layer_map);
+    for layer in layer_map_for_output(output).layers() {
+        layer.send_frame(
+            output,
+            state.start_time.elapsed(),
+            Some(Duration::ZERO),
+            |_, _| Some(output.clone()),
+        );
+    }
+
     workspace.windows().for_each(|e| e.refresh());
     data.display_handle.flush_clients().unwrap();
     state.popup_manager.cleanup();
```
seems to fix the issue. Though there might be a better place to put this idk, and you'd need to do the same for the udev side

**Comment by electron271** [comment]
ty, i will look into implementing this

sorry for the late response, development has been stalled lately
